version: "3"
services:
  nginx:
    build: ./nginx
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /tmp/nginx_log:/var/log/nginx
    ports:
      - "8080:80"
    environment:
      TZ: "Asia/Tokyo"

