AWSTemplateFormatVersion: '2010-09-09'

Resources:
  ArchtectingSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: architecting-on-aws
      GroupDescription: architecting-on-aws
      VpcId:
        Fn::ImportValue:
          !Sub lab-network-VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: architecting-on-aws
